### ISSUE TITLE
pure yarn translator: error: attribute missing

### ISSUE THREAD

**Issue by tgunnoe** [nix-community/dream2nix#105]
There's several quirks with dependency+version lookups in sets on the nodejs side. I found another:

```
error: attribute 'ethers@^5' missing

       at /nix/store/s37pa5yrkb5s8rdkn4rwl1bxx5fbsjcz-source/src/translators/nodejs/pure/yarn-lock/default.nix:63:25:

           62|             yarnName = "${depName}@${semVer}";
           63|             depObject = objectsByKey.yarnName."${yarnName}";
```

In this case, this happens because `ethers@^5` is specified as a `peerDependencies` in `package.json`, and yarn resolves that to a specific `5.x.x` version in `yarn.lock`. And when `peerDependencies` is processed in dream2nix (https://github.com/nix-community/dream2nix/blob/main/src/translators/nodejs/utils.nix#L8), it does not take the resolved package number. So `ethers@^5` is not found when a lookup is attempted.
 
A similar issue is here https://github.com/nix-community/dream2nix/issues/104

**Comment by DavHau** [comment]
Please provide a flake or repo that allows me to easily re-produce the issue. Thanks.

**Comment by tgunnoe** [comment]
@DavHau, sorry about that.  Here's a minimal i tried to come up with.

```
  {
    inputs.dream2nix.url = "github:nix-community/dream2nix";
    inputs.src.url = "github:tgunnoe/dream2nix-peerDependencies-test";
    inputs.src.flake = false;
    outputs = { self, dream2nix, src }@inputs:
      let
        dream2nix = inputs.dream2nix.lib.init {
          systems = [ "x86_64-linux" ];
          config.projectRoot = ./. ;
        };
      in dream2nix.makeFlakeOutputs {
        source = src;
      };
  }
```

**Comment by DavHau** [comment]
Hey, thanks for providing the flake. I tried building all packages and there doesn't seem to be an eval error. Could you verify?
Was it maybe fixed in the meantime?

**Comment by tgunnoe** [comment]
Still seems broken to me.

I did a build of the main package:
`nix build '.#ethers'`

**Comment by DavHau** [comment]
Oh sorry, I confused the flakes. My bad. Now I see the issue.
Hm, I think that yarn does not install peer deps at all by default and that is the reason it cannot be found in the yarn.lock.
I think we should skip peer deps by default. If a peer dep is required for development, then it should be listed under `devDependencies` in `package.json` as well as under `peerDependencies`.

**Comment by DavHau** [comment]
We don't need to have an option. If a peer dep is required for development, then the user can just add it to the `devDependencies` and done. Right?

**Comment by tgunnoe** [comment]
Oh yes, I misunderstood you with "skip peer deps by default".

Sounds good.
