### ISSUE TITLE
Feedback on some overrides.

### ISSUE THREAD

**Issue by happysalada** [nix-community/dream2nix#108]
Hey, this issue is a little rough because it contains various questions.

- Regarding "electron" package build for darwin. The build fails with ` cp: cannot stat '/nix/store/q4yvhf9wy56zxzcmikb8ixaimink5gy7-electron-12.2.3/lib/electron': No such file or directory` . I check in the resulting derivation and there is nothing under /lib, there is a `/bin/electron` though. I was just looking at the electron override inside the repo, and it seems the build step for darwin is putting something inside /bin and not /lib.
- Regarding "7zip-bin" package, the install step on darwin fails with `> /nix/store/m7jxsbvwvkw2zdvlqqqqdbcvr14cp6an-auto-patchelf-hook/nix-support/setup-hook: line 333: -l: command not found`  which is `      segmentHeaders="$(LANG=C $READELF -l "$file")"`. it looks like `$READELF` is not defined on darwin. @Mic92 sorry to bother you with this, but would you know what additional dependency needs to be added on darwin to make this work ?

if you are curious, I'm testing with https://github.com/BoostIO/BoostNote-App

**Comment by DavHau** [comment]
Now addressed by https://github.com/nix-community/dream2nix/pull/109 and https://github.com/nix-community/dream2nix/pull/119
