### ISSUE TITLE
Rust builds - referencing path dependencies outside of a workspace. 

### ISSUE THREAD

**Issue by omerbenamram** [nix-community/dream2nix#113]
Hi!

While playing around using `dream2nix` for our monorepo, I ran into some trouble with crate dependencies that aren't in a workspace.

The monorepo contains projects in many languages, and we currently using nix for
   - rust builds - https://github.com/cargo2nix/cargo2nix
   - python builds - poetry2nix 
The monorepo directory structure is something like:

```
root
   |
   | service
         |
         | -- > serviceA/Cargo.toml // imports ../../lib/libraryA
         | -- > serviceB/Cargo.toml // imports libraryA, but will never import serviceA
         | -- > pythonServiceA/pyproject.toml // imports pythonLibraryA
   | lib
         | -- > libraryA/Cargo.toml // may import libraryB
         | -- > libraryB/Cargo.toml
         | -- > pythonLibraryA/pyproject.toml
```
The python builds work well - the overlay being:
```
        overlay = nixpkgs.lib.composeManyExtensions [
          poetry2nix.overlay
          (final: prev: {
            devEnv = prev.poetry2nix.mkPoetryEnv {
              python = final.pkgs.python38;
              projectDir = ./.;
              overrides = prev.poetry2nix.overrides.withDefaults
                (import ../../tools/nix/python-nix-overlay.nix);
            };
          })
        ];
```

Cargo2nix also works well - but keeping the `Cargo.nix` files in sync with `Cargo.lock` files is somewhat of a hassle.

When trying to build a service using `dream2nix` it would fail with
`error: could not find crate libraryA`

The flake looks like
```
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=release-21.11";
    dream2nix.url = "github:nix-community/dream2nix";
    dream2nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, dream2nix, ... }@inputs:
    let
      dream2nix = inputs.dream2nix.lib.init {
        # modify according to your supported systems
        systems = [ "x86_64-linux" "aarch64-darwin" ];
        config.projectRoot = ./.;
      };
    in dream2nix.makeFlakeOutputs {
      source = ./.;
    };
}
```

I also tried changing `config.projectRoot` to `../..` and using:
```
      sourceOverrides = oldSources: {
        capture_storage_client = builtins.path {
          path = ../../lib/libraryA;
        };
      };
```

But since poetry2nix manages to work around this I reckoned that the rust builder can do it as well 😄 

Thanks!

**Comment by tgunnoe** [comment]
You can run dream2nix in the root repo and use `packageOverrides` to make a patch to copy the library over then patch the sources to point to the library's new location.  kind of like this https://github.com/nix-community/dream2nix/blob/main/overrides/nodejs/default.nix#L809

**Comment by omerbenamram** [comment]
@tgunnoe by "run dream2nix in the root repo" you mean settings `config.projectRoot` to `../..`?
Also - this means patching (using text find replace) each dependency individually AFAIK, which is a little cumbersome.

Also I'm not sure how it will affect caching - but it's a separate issue i suppose.
I was wondering if there is anything that could be done to make this more like poetry2nix (which supports this already).

**Comment by omerbenamram** [comment]
@DavHau  @yusdacra I've checked this out but this doesn't really solve what I was aiming for.
It still fails in the example repository when trying to build inside `service/binary`.

I wanted to avoid keeping a single `flake.nix` file at the root of the monorepo.

Thanks a lot for the effort!

**Comment by DavHau** [comment]
> I wanted to avoid keeping a single flake.nix file at the root of the monorepo.

Why do you want that? I didn't even know it was possible to access parent directories from a flake. But it seems to work as long as it's part of the same repo

**Comment by omerbenamram** [comment]
There are tens of services being managed in the repo, and a few dozen libraries - some of them have customizations in the flake, different target systems etc. There is common nix tooling which is being imported by many of the flakes.

It's the same reason they are not sharing a cargo workspace.

**Comment by DavHau** [comment]
@omerbenamram I just tested with your repo and both the top level flake as well as the one in `./service/binary` work without any problem.
see: https://github.com/DavHau/dream2nix-issue-113
Maybe you just forgot to update dream2nix when you tested.

**Comment by omerbenamram** [comment]
@DavHau My bad! I've tried setting `config.projectRoot` to `../..` - but in your working example it's `source` under `makeFlakeOutputs`.

It's working file on my linux machine - but it breaks on mac with:

```
❯ nix build .#packages.aarch64-darwin.binary

error: builder for '/nix/store/0i9km7lz45i10h5frnskmybpnjgm0z72-binary-0.1.0.drv' failed with exit code 1;
       last 9 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/x1p22sam64s7rpj07mfz2difxiav4mw7-fvywq19s7rnscjljnka87knyklvrpfxn-source/service/binary
       > source root is binary
       > Executing cargoSetupPostUnpackHook
       > Finished cargoSetupPostUnpackHook
       > patching sources
       > updateAutotoolsGnuConfigScriptsPhase
       > configuring
       > mv: cannot stat '/build/.cargo/config': No such file or directory
       For full logs, run 'nix log /nix/store/0i9km7lz45i10h5frnskmybpnjgm0z72-binary-0.1.0.drv'.
```

Maybe you have an idea where this could happen 😅?

**Comment by yusdacra** [comment]
@omerbenamram can you try PR https://github.com/nix-community/dream2nix/pull/130 and see if that works out for you?
