### ISSUE TITLE
Improve and document dependency injection API

### ISSUE THREAD

**Issue by DavHau** [nix-community/dream2nix#121]
see: https://github.com/nix-community/dream2nix/issues/117#issuecomment-1107676009

**Comment by DavHau** [comment]
Documentation is already done via example flake in readme

**Comment by happysalada** [comment]
This is looking really good!
One point that I would add, is instead of using foo, I would add another example with the @ sign (because those appear as __at__ in nix cli, it's not immediately obvious. Let me add something and you can tell me what you think.
