### ISSUE TITLE
Unexplained abbreviations

### ISSUE THREAD

**Issue by puppe** [nix-community/dream2nix#132]
Some abbreviations are used in the documentation that are never explained. What do IFD and FOD stand for? I genuinely don‘t know. Most people probably know that UX stands for “user experience” but maybe not everyone.

Could you please write out these terms at least once before you introduce an abbreviation?

**Comment by zarak** [comment]
I was also unfamiliar with these terms. It might be worth linking to this [glossary](https://nixos.wiki/wiki/Glossary).

**Comment by puppe** [comment]
Thanks for fixing that! I wanted to do it today but you were faster.
