### ISSUE TITLE
Produce some video tutorials

### ISSUE THREAD

**Issue by DavHau** [nix-community/dream2nix#15]
Content could be:
  - walk through the packaging workflow with dream2nix
  - show how to implement a new translator
  - show how to implement a builder

**Comment by JonathanLorimer** [comment]
Is there any written documentation on this?

**Comment by DavHau** [comment]
Currently there isn't a lot.
[dreampkgs](https://github.com/nix-community/dreampkgs) has a list of the basic commands for creating and updating packages and a link to the override system docs.

For implementing a translator and builder there is the `.#contribute` flake app which will initialize templates with many comments inside. see [contributors-guide](https://github.com/nix-community/dream2nix/blob/main/docs/contributors-guide.md)

**Comment by DavHau** [comment]
By now we have the docs website with several guides etc. It's probably not useful to waste time on making videos before our API is stabilized. Closing for now.
