### ISSUE TITLE
haskell: detect GHC version during translation

### ISSUE THREAD

**Issue by DavHau** [nix-community/dream2nix#177]
see: https://github.com/nix-community/dream2nix/pull/164#discussion_r895712272
Also the hidden packages should be dynamically generated depending on the ghc version.
This can be done by parsing this file:
https://gitlab.haskell.org/bgamari/ghc-utils/-/blob/master/library-versions/pkg_versions.txt

**Comment by bezmuth** [comment]
@DavHau why is generating the list of hidden packages required? If they are all contained within ghc why should it be needed to know what version these packages are?

**Comment by DavHau** [comment]
> @DavHau why is generating the list of hidden packages required? If they are all contained within ghc why should it be needed to know what version these packages are?

I think we only want to specify a dependency on a builtin package if the required version is different from the one shipped with ghc. If a default version of a builtin is required, the nixpkgs haskell architecture wants this package to be `null`.
But maybe this could be solved differently as well. I'm not sure.

**Comment by DavHau** [comment]
> @DavHau why is generating the list of hidden packages required? If they are all contained within ghc why should it be needed to know what version these packages are?

I think we only want to specify a dependency on a builtin package if the required version is different from the one shipped with ghc. If a default version of a builtin is required, the nixpkgs haskell architecture wants this package to be `null`.
But maybe this could be solved differently as well. I'm not sure.

**Comment by DavHau** [comment]
> @DavHau why is generating the list of hidden packages required? If they are all contained within ghc why should it be needed to know what version these packages are?

I think we only want to specify a dependency on a builtin package if the required version is different from the one shipped with ghc. If a default version of a builtin is required, the nixpkgs haskell architecture wants this package to be `null`.
But maybe this could be solved differently as well. I'm not sure.

**Comment by DavHau** [comment]
This has been solved by @leungbk
