### ISSUE TITLE
Can the translator provide things to the overrides?

### ISSUE THREAD

**Issue by wmertens** [nix-community/dream2nix#233]
The translator for nodejs accepts the nodejs version, it would be great if the overrides could use that.

**Comment by DavHau** [comment]
Is the pure translation affected by the nodejs version in any way? If not, I think we should remove that as a translator argument.
Setting the nodejs version via override might not be the right choice, as this would allow to use different nodejs version within one dependency tree, which doesn't make sense.

This might probably be a case for subsystem specific settings https://github.com/nix-community/dream2nix/issues/241

**Comment by wmertens** [comment]
The problem is when overrides need to use information about the specific nodejs package. However, I now realize that `nodeSources` is just available as an environment variable and the correct `node` version is in the path.

Probably all sorts of necessary information will always be able to be injected as variables to the build scripts, so I think this issue can be closed.
