### ISSUE TITLE
per-subsystem subsystemInfo definition/parser?

### ISSUE THREAD

**Issue by wmertens** [nix-community/dream2nix#241]
It feels weird to let subsystemInfo be handled by translator only, especially since there can be many translators, passing settings to the builder is arbitrary, and I guess the discoverer can't see them?

How about a per-subsystem settings module that defines the flags and optionally transforms them?

Then they could also be made available to the overrides?

**Comment by DavHau** [comment]
> How about a per-subsystem settings module

Sounds good. Sounds like a use case for nixos modules.

> Then they could also be made available to the overrides?

If we were using nixos modules for our interfaces including for configuring individual packages, there won't be a need of `overrides` anymore.

**Comment by wmertens** [comment]
Right - I think the modules idea is good, let's discuss in #156
