### ISSUE TITLE
dream.lock: injecting existing dependency

### ISSUE THREAD

**Issue by wmertens** [nix-community/dream2nix#244]
To fix packages that don't specify all their dependencies, it would be nice to have access to the dependencies so that you could do something like

```nix
dependencies: let
  getPkg = name: let version = elemAt 0 (attrNames dependencies.${name}); in { inherit name version; };
  missingDep = getPkg "foo";
  broken = getPkg "broken";
  brokenDeps = oldDeps.${broken.name}.${broken.version};
in
  dependencies // { ${broken.name}.${broken.version} = brokenDeps ++ [missingDep]; }
```

So then first the translator runs and then the dependencies can be patched before the cycle detection.

That way you can use the translator to determine the package details by adding the missing dep to the root dependencies and letting the translator resolve the impurity.

This could also be used to force using a certain version of a package etc.

For even more flexibility, the sources could also be passed into the function (or to a separate function) so they can be patched too.

**Comment by wmertens** [comment]
It would also be great if this could be integrated with the overrides system. So then a known-broken package can always have the correct dependency injected.

Or maybe that is already possible?

**Comment by DavHau** [comment]
Currently the way to inject dependencies manually is using the `inject` parameter as seen in the example of the main readme.
This is currently injected at evaluation time after translation. This will work with any translator and does not need to be supported by a translator.

Also for some translators, it is possible to add extra dependencies via argument. For example the pip translator allows specifying `extraSetupDeps`.

We do not have a way of adding deps via the override system so far. Maybe this could be integrated better. But I think first, we should have a proper module system in place before extending the current `hacky` API any more.

There were some discussions here: https://github.com/nix-community/dream2nix/issues/156
And I recently opened a PR to move functionality to nixos modules: https://github.com/nix-community/dream2nix/pull/249

**Comment by DavHau** [comment]
Closing as injecting existing dependencies is already possible.
There are issues tracking improvements: https://github.com/nix-community/dream2nix/issues/361
If there are some other specific things we need to improve, let's open a specific issue for that
