### ISSUE TITLE
PR 249 breaks rust build

### ISSUE THREAD

**Issue by johnae** [nix-community/dream2nix#254]
This commit: https://github.com/nix-community/dream2nix/commit/d2b389de98c54d45db0134984b7d8e209cba6907 - part of PR https://github.com/nix-community/dream2nix/pull/249, results in an error that I didn't get in the previous commit https://github.com/nix-community/dream2nix/commit/07547c2284e9f521013556f361996be9aba3a3fd

```sh
❯ nix build '.#nu'
warning: Git tree '/home/john/Development/world' is dirty
warning: Using saved setting for 'extra-experimental-features = nix-command flakes' fr
om ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-substituters = https://nix-community.cachix.or
g https://insane.cachix.org https://cachix.cachix.org' from ~/.local/share/nix/trusted
-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = nix-community.cachix.org
-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= insane.cachix.org-1:cLCCoYQKkmEb/M88UI
ssfg2FiSDUL4PUjYj9tdo4P8o= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSo
MckM=' from ~/.local/share/nix/trusted-settings.json.
error: attribute 'nu-pretty-hex' missing

       at /nix/store/76yd1ixrinygifpwqp7vhzjy4l9g483h-source/src/lib/simpleTranslate2.
nix:196:15:

          195|             children =
          196|               depGraphWithFakeRoot."${node.name}"."${node.version}";
             |               ^
          197|
(use '--show-trace' to show detailed location information)
```

It's a Rust build so not sure what `node` has to do with it, though I'm very unfamiliar with the internals of this project.

**Comment by yusdacra** [comment]
This shouldn't be related to the Rust subsystem I think but rather a more general issue I believe. But something might have changed that might have broken the code in the Rust subsystem. I'm not exactly sure why however. If you post a flake here I can debug it.

**Comment by yusdacra** [comment]
Does https://github.com/nix-community/dream2nix/commit/0131c22c369f8c4c661aea7a395e94669a7f5974 fix your issue?

**Comment by johnae** [comment]
Thanks @yusdacra. Seems that fixes the issue.
