### ISSUE TITLE
Include meta in package derivations

### ISSUE THREAD

**Issue by khaled** [nix-community/dream2nix#292]
I'm using the following to generate a basic BOM:
```
nix bundle .#my-package --bundler bundlers#toReport
```

The report will include node packages, but the they are missing license and maintainer information.  For example:

```
express-4.18.1 (no license) maintained by nobody
```

It would be nice if derivations generated for each package included meta extracted from their `package.json`s.  Typically they will include license, author, and contributor information.  According to the [package.json docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license), licenses should generally use SPDX identifiers, which should hopefully make them easily to translate to `meta.license`.

**Comment by yusdacra** [comment]
I do this in `nix-cargo-integration` for Cargo projects. I can upstream that logic here and polish it up and add it to nodejs, rust and etc. subsystems.

**Comment by khaled** [comment]
@yusdacra that sounds like a lovely idea :)

**Comment by yusdacra** [comment]
I made #294 which adds licenses info for nodejs and rust. However, the report still doesn't work, because it doesn't handle multiple licenses (see https://github.com/NixOS/bundlers/blob/master/report/default.nix#L162-L168). But this isn't a dream2nix issue so it should be reported to bundlers repo.
