### ISSUE TITLE
How to apply packageOverrides before translating?

### ISSUE THREAD

**Issue by tinybeachthor** [nix-community/dream2nix#306]
I need to fixup something in a package manifest (composer.json) before the package is translated impurely.

As far as I see, the packageOverrides are only applied while building the packages.

It would be nice to have a way to override packages before translation, maybe applying `postUnpack`s from the `packageOverrides` to sources before translation?

**Comment by yusdacra** [comment]
Use `sourceOverrides`, that sounds exactly like what you want?

**Comment by tinybeachthor** [comment]
Yes that could work.

Can I define `sourceOverrides` globally? Like `packageOverrides` in https://github.com/nix-community/dream2nix/tree/main/overrides?

**Comment by yusdacra** [comment]
You can't, that is only of `packageOverrides`. I'm not sure what you mean "globally" though? You can just define it as the README shows, just pass it to `makeFlakeOutputs` / `makeOutputs`. You can put it in another file if you want and just `import ./sourceOverrides.nix {inherit oldSources inputs;}`.

**Comment by tinybeachthor** [comment]
Yeah you're right. I was thinking about a way to upstream the override, but that does not make much sense after all.
