### ISSUE TITLE
Discoverers should not be part of Translator

### ISSUE THREAD

**Issue by hsjobeki** [nix-community/dream2nix#342]
_Currently_: Discoverer can be either implemented directly inside a translator or in a separate file.

It should not be possible to define a 'discoverProject' function inside the translator as they are very different concerns.
Discovering the project belongs to a phase where some preparation work Is done; where d2n collects information about the subsystem.
Mixing those concerns doesn't seem clean architecture.

- [ ] Translator should __only__ translate
- [ ] preparation and collection of information about the subsystem is a __general pre-phase__. Not only for the translator.

Thus it makes no sense to have it in the translator.

**Comment by yusdacra** [comment]
I think this does make sense, maybe we should just introduce a function in dlib that will let users create a discoverer easily just by passing it a condition (like how discoverProject is currently). It would make things more clear which will be nice. @DavHau what do you think about this?

**Comment by DavHau** [comment]
> It should not be possible to define a 'discoverProject' function inside the translator as they are very different concerns

Technically those are still different concerns. It's just syntactic sugar, that you can create a discoverer quickly by defining `discoverProject` in your translator. The alternative would be to create a new file under `./discoverers`. Both are equivalent in terms of when they are processed. Logically, the `discoverProject` does not have any relation to the translator itself, other than it being defined in the same file.

I want to make it as simple as possible for people to add support for new ecosystems. Having the option to define `discoverProject` directly in the translator, allows people to just go ahead without having to understand what a discoverer is and how it works.

What we could do to fix the mental overhead problem, is to change/fix the `contribute` app to always create a `discoverer`, `translator` and `builder` at once, making it really clear for the user which parts need to be edited.

Having the discoverer template based on a helper function that only requires a regex or file ending, also makes sense.

**Comment by hsjobeki** [comment]
Great idea! Love it.
We should just improve the  contribute "script" with more clear steps
 1. Discoverer
 2. Translater
 3. Builder
 And all those should come in seperate files with a nice introduction how to setup and how to test your progress
