### ISSUE TITLE
Proposal: Add support for (npm) ssh dependencies. 

### ISSUE THREAD

**Issue by hsjobeki** [nix-community/dream2nix#343]
### Many users, like organizations, companies, etc. have a mixture of open-source and private dependencies in their projects.

npm supports the following syntax: 
`git+ssh://git@github.com:npm/package@version`

poetry supports
`poetry add <repo> --git ssh://git@github.com/<org>/<repo>.git`

and so on in other package managers

---

-> This could be added by invoking the fetchgitPrivate when a ssh dependency is detected in the lockfile

FetchGitPrivate is doing a git checkout via SSH. This requires setting up an SSH configuration describing which SSH key to use when connecting to GitHub.

This configuration could look like this:

```txt
Host [github.com](http://github.com/)
IdentityFile /etc/ssh/ssh_host_rsa_key
```

**Comment by DavHau** [comment]
AKAIK, `builtins.fetchGit` is able to fetch via ssh using the users local ssh config. So it's probably just a matter of parsing these entries correctly with our translators and making sure that our `src/fetchers/git` accepts these URLs.

**Comment by hsjobeki** [comment]
Update: it seems the ssh protocol, basically just works. (As you said)

- still npm does only fetch files specified in package.json -> https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files
- d2n does fetch the whole repository.
