### ISSUE TITLE
rust: packages generated via the indexer fail

### ISSUE THREAD

**Issue by DavHau** [nix-community/dream2nix#368]
see: https://hercules-ci.com/github/nix-community/dream2nix-auto-test/jobs/209
... all with the same error:
```
error: the lock file /build/unpack-ordered-float-3.4.0/Cargo.lock needs to be updated but --frozen was passed to prevent this
```

**Comment by yusdacra** [comment]
They seem to build fine with the crane builder, so there is something wrong with the build-rust-package builder I think. I made https://github.com/nix-community/dream2nix-auto-test/pull/2 which makes the index use crane builder, I will investigate why build-rust-package fails.

**Comment by yusdacra** [comment]
I pushed https://github.com/nix-community/dream2nix/commit/25b6aba079c87ad2d3f064f2ef2ecedbde7b9b97 which should fix the issue of build-rust-package failing, I'm not sure why crane didn't fail with the same errors in this case, but it should be fixed now anyways.
