### ISSUE TITLE
Templates are not able to be used

### ISSUE THREAD

**Issue by Rekkyn** [nix-community/dream2nix#400]
Running the command `nix flake init -t github:nix-community/dream2nix#simple` results in this error:
```
error: opening directory '/nix/store/zmahd7xchd72zgyxsk3iya74s5cyh592-source/templates/templates/simple': No such file or directory
```

**Comment by yusdacra** [comment]
Should be fixed in https://github.com/nix-community/dream2nix/commit/a5e098038c42528bf4dff2db6cb958b1777b00e3
