### ISSUE TITLE
Disable automatic discovery of projects by default

### ISSUE THREAD

**Issue by DavHau** [nix-community/dream2nix#407]
The automatic discovery was a nice idea but seems to lead to too many issues right now.
Projects are detected which should not be detected, people are confused, nix evaluation is crashing, etc.

For most people it's probably better to specify the projects manually.

For the `makeFlakeOutputs` interface, we could do the following:
- introduce a new field `apiVersion` which defaults to `0` but if set two `1`, disables automatic project discovery and forces the user to specify the projects manually. (this will become the default for our flake templates and examples)
- introduce a new field `discoverProjects` which if set to `true` re-enables automatic project discovery even if `apiVersion = 1`.
- change all examples under `./examples` to use `apiVersion = 1` and specify projects manually. They should basically use [this style](https://github.com/nix-community/dream2nix/blob/ce047a9ceaf1040dc14e393cc3243d22dd0dbcdc/examples/_d2n-define-projects-manually/flake.nix) instead of [this style](https://github.com/nix-community/dream2nix/blob/ce047a9ceaf1040dc14e393cc3243d22dd0dbcdc/examples/nodejs_prettier/flake.nix)
- provide a CLI utility that discovers projects and dumps them to a `projects.toml` (just a `nix eval` wrapper around `framework.functions.discoverers.discoverProjects`)
- change the basic flake template, to read the projects list from the `projects.toml` file that doesn't exist by default.
- if user initializes our basic flake template and does not specify any project, crash and instruct the user on how to use the new CLI urtility to generate the `projects.toml`.

What do you think about that?
@yusdacra @chaoflow @phaer @hsjobeki

**Comment by phaer** [comment]
I agree that it's probably I good idea to disable auto discovery at by default. 

Personally I wouldn't feel like it's necessary to keep backwards-compatibility as the upgrade should be rather clear and simple, but as I am very new  to this project I might be missing context and/or use cases here.

Whats the rationale behind `projects.toml`? Is it because toml might be friendlier to users new to nix? Otherwise wouldn't a cli which outputs a nix snippet to include in your flake (or default.nix) work just as well?

> They should basically use [this style](https://github.com/nix-community/dream2nix/blob/ce047a9ceaf1040dc14e393cc3243d22dd0dbcdc/examples/_d2n-define-projects-manually/flake.nix) instead of [this style](https://github.com/nix-community/dream2nix/blob/ce047a9ceaf1040dc14e393cc3243d22dd0dbcdc/examples/nodejs_prettier/flake.nix)

Just a heads-up, the first link is broken due to an extra "x" at the end (fixed in my quote)

**Comment by yusdacra** [comment]
I agree with this mostly, but I'd rather not bother with keeping backwards compat. I think instead we should just `builtins.throw` if `projects` is not specified and point users to documentation on how to upgrade. And if we are going to add a `projects.toml` file for the default example, IMO we should consolidate both `nix_systems` and `projects.toml` into one file. Having two files (with different formats) is more confusing for users.

**Comment by chaoflow** [comment]
I'm unsure about auto-discovery and need a couple of real-world examples before having an opinion as of when auto would be good: single package python project, could be one, however, that feels more like having sane defaults.

- I'd disable auto-discover by default, not sure whether to even offer an option to turn it on
- also don't see a need for backwards compatibility (there is a clear warning on top of the readme - it could be in bold font, but ...)
- We should introduce an api version, once we're ready to support that version alongside a potentially instable api
- I'd avoid an extra file and like @phaer 's idea about the nix snippet -- however. How many projects do people have within a repo? If we only have to point at the directories, I would not bother with the snippet but just have people write the couple of lines manually

I'd rather focus on sane defaults and having a minimal flake.nix for standard use cases, then code generation.

**Comment by DavHau** [comment]
> Whats the rationale behind `projects.toml`? Is it because toml might be friendlier to users new to nix? Otherwise wouldn't a cli which outputs a nix snippet to include in your flake (or default.nix) work just as well?

Dumping to toml or json is just quicker to implement. I don't know a library that dumps a data structure to a `.nix` file. It just requires implementing more logic. Also TOML is a pretty nice format. But I'm fine with nix as well.

OK, then let's implement that change

**Comment by DavHau** [comment]
reviews of [my PR](https://github.com/nix-community/dream2nix/pull/415) much appreciated
