### ISSUE TITLE
Confusing default package in ./examples/python_pip

### ISSUE THREAD

**Issue by phaer** [nix-community/dream2nix#423]
```
nix flake show -L ./examples/python_pip
```
outputs the following packages:
```
└───packages
    └───x86_64-linux
        ├───default: package 'llhttp-6.0.6'
        ├───llhttp: package 'llhttp-6.0.6'
        ├───main: package 'main'
        └───resolveImpure: package 'resolve'
```

which seems wrong to me. In my understanding, `default` should refer to `main` - a python application - here, not to `llhttp`, a dependency of said python project.

**Comment by DavHau** [comment]
fixed this via https://github.com/nix-community/dream2nix/commit/e82afbcb55433ef739d2ab1f31783d79380c645c but now there is no `default` package anymore. This can be fixed in the python builder

**Comment by phaer** [comment]
Took me a while, but i can confirm this is fixed in main.
