### ISSUE TITLE
flake interface: source, projectRoot vs relPath are confusing.

### ISSUE THREAD

**Issue by hsjobeki** [nix-community/dream2nix#467]
Nowadays we have three points where you can configure source paths:

This just works fine and doesnt require any more configuration when flake.nix and the node project is in the source of your git repository.
But as soon as you have a nested folder and multiple sub-projects this leads to confusion.

Why do i have 3 different options, also their names are non-intuitive. 

I guess source is equal to `src` in the underlying mkDerivation, so I'd like to keep its name to make that clear.

also `projectRoot` and `relPath` seem a little weird to me, didnt understand quite yet what they actually do.

```nix
# flake.nix
config.projectRoot = ./website;
source = ./website;

# projects.toml
relPath = "website"
```

@DavHau  If you are already considering to refactor the flake interface you might take that into account.

**Comment by phaer** [comment]
I'll close this for now in an effort the keep the list of open issues review-able, but feel free to re-open if you think that it's still confusing in the v1 api draft.
