### ISSUE TITLE
Failed to detect project in @quick-start/electron

### ISSUE THREAD

**Issue by dnswd** [nix-community/dream2nix#484]
### What to expect?  
`detect-project` should properly detect an electron boilerplate project (`@quick-start/electron`)

### What happened?  
I got the following error when trying to detect project a brand new electron boilerplate.
```
error: [json.exception.parse_error.101] parse error at line 2, column 1: syntax error while parsing object key - unexpected end of input; expected string literal
(use '--show-trace' to show detailed location information)
```

### What have I done?
`nix run github:nix-community/dream2nix#detect-projects . --show-trace` results in the following output:
```
# projects.toml file describing inputs for dream2nix
#
# To re-generate this file, run:
#   nix run .#detect-projects $source
# ... where `$source` points to the source of your project.
#
# If the local flake is unavailable, alternatively execute the app from the
# upstream dream2nix flake:
#   nix run github:nix-community/dream2nix#detect-projects $source

error: [json.exception.parse_error.101] parse error at line 2, column 1: syntax error while parsing object key - unexpected end of input; expected string literal
(use '--show-trace' to show detailed location information)
```

Not so helpful, so I tried to read the `detect-project` source but I'm not sure which part went wrong. I only have been using nix for a couple months, I don't know what else should I do to debug this problem.

### Steps to reproduce
1. `nix-shell -p yarn`
2. `yarn create @quick-start/electron dummy-project --template react-ts`
3. `cd dummy-project`
4. `nix run github:nix-community/dream2nix#detect-projects . > projects.toml`

**Comment by niklaskorz** [comment]
Experiencing the same error in a different project

**Comment by niklaskorz** [comment]
It looks like this is caused by detect-projects scanning `node_modules` (which are listed in gitignore) as well? Removing all local `node_modules` folders made it pass.

**Comment by dnswd** [comment]
Can confirm it works after deleting `node_modules`. Closing this issue.

**Comment by raboof** [comment]
I got hit by this as well - would be nice to have some better diagnostic output ;)
