### ISSUE TITLE
https://dream2nix.dev/ is down

### ISSUE THREAD

**Issue by Atry** [nix-community/dream2nix#505]
<img width="1069" alt="截屏2023-04-17 10 48 57" src="https://user-images.githubusercontent.com/601530/232568337-de8803c1-ddda-47d7-b885-3dee915b44c1.png">

 
```
nix-repl> builtins.fetchTarball "https://dream2nix.dev/tarball/1.0"
warning: error: unable to download 'https://dream2nix.dev/tarball/1.0': SSL connect error (35); retrying in 349 ms
warning: error: unable to download 'https://dream2nix.dev/tarball/1.0': SSL connect error (35); retrying in 638 ms
warning: error: unable to download 'https://dream2nix.dev/tarball/1.0': SSL connect error (35); retrying in 1046 ms
warning: error: unable to download 'https://dream2nix.dev/tarball/1.0': SSL connect error (35); retrying in 2500 ms
error: unable to download 'https://dream2nix.dev/tarball/1.0': SSL connect error (35)
```

**Comment by phaer** [comment]
Hello,

If you check with e.g. `curl -k` you'll see that dream2nix.dev is just a "domain parked" site atm - and the registrar seems to use quite old SSL ciphers. 

As the only location referring to that URL are the v1 docs: the v1 api isn't actually a supported thing yet.
