### ISSUE TITLE
How to add support to preexisting flake?

### ISSUE THREAD

**Issue by yajo** [nix-community/dream2nix#570]
The docs tell how to use the `makeFlakeOutputs` function: https://github.com/nix-community/dream2nix/blob/3772175693d6888d7428dec0ac8af63eb3ee31b3/README.md?plain=1#L74-L86

However, what happens if I already have a flake and I just want to add some of the d2n features I need? How can I add support for `detect-projects` or `resolveImpure` while still keeping all the rest of my flake untouched?

Currently it seems like d2n tries to _replace_ all the flakes interface with its own function, instead of living along with it if you already are using flakes...

**Comment by DavHau** [comment]
Exporting flakes was a bad design choice, and will be fixed once [v1 API is released](https://github.com/nix-community/dream2nix/issues/507).

Closing this as won't fix
