### ISSUE TITLE
feat: let users be able to specify a `ref` alongside a `rev` for the `git` fetcher

### ISSUE THREAD

**Issue by yusdacra** [nix-community/dream2nix#66]
This is good for not using `allRefs`, which can slowdown the fetch if there are many refs. Translators that have access to the `ref` alongside a `rev` can use this to not require `allRefs` usage (for example, `Cargo.lock` files can include a `branch` or a `tag` for git dependencies, alongside the usual git revision).

**Comment by DavHau** [comment]
Sounds good to me
