### ISSUE TITLE
Dependency resolution is case-sensitive for pdm

### ISSUE THREAD

**Issue by purepani** [nix-community/dream2nix#743]
For some python projects, a dependency of a package may have case sensitivity. However, the top level names of packages in the lock file are always lowercase. This means that when recursing through dependencies, if dependencies are lowercase, they might not be found in the lock file. An example package where this causes an issue is Flask. 

Since the parsing is done by pyproject.nix, it might be better to fix that upstream there.

**Comment by FRidh** [comment]
You mean all names should always be normalized?

**Comment by purepani** [comment]
That's at least the simplest solution I can think of.

If the dependency of a package has some non-standard normalization, then it wouldn't match with what's in the lock file.
