### ISSUE TITLE
Basic Documentation

### ISSUE THREAD

**Issue by tobiasBora** [nix-community/dream2nix#842]
It seems like dream2nix is a great tool… but it has a really poor (if any) beginner-friendly documentation. Why isn't there in [the documentation](https://nix-community.github.io/dream2nix/) a simple set of instructions to set-up dream2nix? Seems like it would be much more helpful than a few, possibly outdated, examples.

**Comment by supermarin** [comment]
@DavHau can this please be addressed?

The current state of the docs is completely unusable. 
The `-> to the docs` link recursively links to the homepage.
Any pointers on how to get started with a basic python environment would be appreciated.

**Comment by ahihi** [comment]
just chiming in to point out that there are new [Getting started](https://dream2nix.dev/guides/getting-started/) and [Python & pip](https://dream2nix.dev/guides/pip/) guides on the website. i found these very helpful, thanks a lot! :)
