### ISSUE TITLE
Setuptools Collision

### ISSUE THREAD

**Issue by usmcamp0811** [nix-community/dream2nix#843]
I tried updating my [`label-studio'](https://gitlab.com/usmcamp0811/campground-packages/-/blob/main/packages/label-studio/default.nix?ref_type=heads) and I keep getting:

```
       >  'recursive': True,
       >  'runtime_dependencies': []}
       > auto-patchelf: 0 dependencies could not be satisfied
       > pythonCatchConflictsPhase
       > Found duplicated packages in closure for dependency 'setuptools':
       > 	setuptools 68.2.2.post0 (/nix/store/y8yq448xka665bqyd5gvdhajqdbsnyys-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools-68.2.2.post0.dist-info)
       > 	setuptools 68.2.2 (/nix/store/hbdrvd22dwndf6sjnydwrmv3z05a330i-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools-68.2.2.dist-info)
       >
       > Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
       For full logs, run 'nix log /nix/store/rmk7m46rgcs27srbm7qh0vhkkbv3cqr8-python3.11-label_studio-1.11.0.drv'.
```

I've tried to change the version of `setuptools` I am requiring to be `68.2.2.post0` but then the `pip` update fails. My best guess right now is that maybe the `post0` was removed from `pypi`?

**Comment by DavHau** [comment]
The cause of this is most likely: https://github.com/NixOS/nixpkgs/issues/283695

To ignore the collision you can just set 'buildPythonPackage.ignoreCollisions = true' for the dependency which fails to build

**Comment by mcamp-ata** [comment]
I tried adding that and got errors telling me it wasn't a thing.. I will need to explore this more when I get some time. I did a `flake update` and thought I had the latest of `dream2nix` but maybe not.

**Comment by DavHau** [comment]
sorry, I meant 'catchConflicts' instead of 'ignoreCollisions'. You should be able to see it in the dream2nix docs under buildPythonPackage

**Comment by usmcamp0811** [comment]
yep that worked.. thanks!
