### ISSUE TITLE
[help] usage of multi-derivation-package

### ISSUE THREAD

**Issue by willruggiano** [nix-community/dream2nix#919]
I know it's marked as internal/experimental but I have a usecase for using it and can't really figure out how to do so, even after looking at the [initial commit](https://github.com/nix-community/dream2nix/commit/c3c5769abaa954766b6a4b8ab193d7538c02b12e) and specifically the test case for this module.

Is this intended to be used for packages that have multiple _outputs_? Like out, man, bin, lib, etc sort of things?

**Comment by DavHau** [comment]
It was meant as a helper to create packages with multiple outputs, but each output defined by a separate derivation
